//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssEmbly.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AssEmbly.Resources.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given bytes do not start with the correct header.
        /// </summary>
        internal static string AAP_Error_Invalid_Bad_Header {
            get {
                return ResourceManager.GetString("AAP_Error_Invalid_Bad_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are not enough bytes in the given array to be a valid AAP file.
        /// </summary>
        internal static string AAP_Error_Invalid_Not_Enough_Bytes {
            get {
                return ResourceManager.GetString("AAP_Error_Invalid_Not_Enough_Bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided debug information file was in an invalid format.
        /// </summary>
        internal static string DebugInfo_Error_Invalid_Format {
            get {
                return ResourceManager.GetString("DebugInfo_Error_Invalid_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided debug information file was created for a different version of AssEmbly.
        /// </summary>
        internal static string DebugInfo_Error_Wrong_Version {
            get {
                return ResourceManager.GetString("DebugInfo_Error_Wrong_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , .
        /// </summary>
        internal static string Generic_CommaSeparate {
            get {
                return ResourceManager.GetString("Generic_CommaSeparate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2022-2024  Ptolemy Hill
        ///Licensed under GPLv3; run the &quot;license&quot; operation for details..
        /// </summary>
        internal static string Generic_Copyright_Header {
            get {
                return ResourceManager.GetString("Generic_Copyright_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flags:.
        /// </summary>
        internal static string Generic_Flags_Header {
            get {
                return ResourceManager.GetString("Generic_Flags_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X}.
        /// </summary>
        internal static string Generic_Hex_Value {
            get {
                return ResourceManager.GetString("Generic_Hex_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     {0}: {1}.
        /// </summary>
        internal static string Generic_Indented_Key_Value {
            get {
                return ResourceManager.GetString("Generic_Indented_Key_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        internal static string Generic_Key_Value {
            get {
                return ResourceManager.GetString("Generic_Key_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to continue....
        /// </summary>
        internal static string Generic_Press_Any_Key_To_Continue {
            get {
                return ResourceManager.GetString("Generic_Press_Any_Key_To_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (0b{0}).
        /// </summary>
        internal static string Generic_Register_Binary_Value {
            get {
                return ResourceManager.GetString("Generic_Register_Binary_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (&apos;{0}&apos;).
        /// </summary>
        internal static string Generic_Register_Char_Value {
            get {
                return ResourceManager.GetString("Generic_Register_Char_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ({0}).
        /// </summary>
        internal static string Generic_Register_Denary_Value {
            get {
                return ResourceManager.GetString("Generic_Register_Denary_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ({0:0.0###############}).
        /// </summary>
        internal static string Generic_Register_Floating_Value {
            get {
                return ResourceManager.GetString("Generic_Register_Floating_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (0x{0:X}).
        /// </summary>
        internal static string Generic_Register_Hex_Value {
            get {
                return ResourceManager.GetString("Generic_Register_Hex_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rpo.
        /// </summary>
        internal static string Generic_Register_rpo {
            get {
                return ResourceManager.GetString("Generic_Register_rpo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rsb.
        /// </summary>
        internal static string Generic_Register_rsb {
            get {
                return ResourceManager.GetString("Generic_Register_rsb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rso.
        /// </summary>
        internal static string Generic_Register_rso {
            get {
                return ResourceManager.GetString("Generic_Register_rso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register states:.
        /// </summary>
        internal static string Generic_Register_States_Header {
            get {
                return ResourceManager.GetString("Generic_Register_States_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Generic_Severity_Error {
            get {
                return ResourceManager.GetString("Generic_Severity_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestion.
        /// </summary>
        internal static string Generic_Severity_Suggestion {
            get {
                return ResourceManager.GetString("Generic_Severity_Suggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Generic_Severity_Warning {
            get {
                return ResourceManager.GetString("Generic_Severity_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0}.
        /// </summary>
        internal static string Generic_Single_Indent {
            get {
                return ResourceManager.GetString("Generic_Single_Indent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0}:{1}.
        /// </summary>
        internal static string Generic_Single_Indented_Key_Value {
            get {
                return ResourceManager.GetString("Generic_Single_Indented_Key_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Generic_Unknown {
            get {
                return ResourceManager.GetString("Generic_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unmapped.
        /// </summary>
        internal static string Generic_Unmapped {
            get {
                return ResourceManager.GetString("Generic_Unmapped", resourceCulture);
            }
        }
    }
}
