//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssEmbly.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_Processor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_Processor() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AssEmbly.Resources.Localization.Strings.Processor", typeof(Strings_Processor).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A program is already loaded in this processor..
        /// </summary>
        internal static string Error_Already_Loaded {
            get {
                return ResourceManager.GetString("Error_Already_Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot execute load external assembly instruction if an assembly is already loaded.
        /// </summary>
        internal static string Error_Assembly_Already_Open {
            get {
                return ResourceManager.GetString("Error_Assembly_Already_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified external assembly file is invalid.
        /// </summary>
        internal static string Error_Assembly_Invalid {
            get {
                return ResourceManager.GetString("Error_Assembly_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified external assembly file does not contain a global public static class named &apos;AssEmblyInterop&apos;.
        /// </summary>
        internal static string Error_Assembly_No_Type {
            get {
                return ResourceManager.GetString("Error_Assembly_No_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified external assembly file could not be found.
        /// </summary>
        internal static string Error_Assembly_Not_Found {
            get {
                return ResourceManager.GetString("Error_Assembly_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot execute instruction if an external assembly is not loaded.
        /// </summary>
        internal static string Error_Assembly_Not_Open {
            get {
                return ResourceManager.GetString("Error_Assembly_Not_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred trying to load the external assembly.
        /// </summary>
        internal static string Error_Assembly_Unknown {
            get {
                return ResourceManager.GetString("Error_Assembly_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error was thrown by an external method ({0} -&gt; {1}):
        ///        {2}: {3}.
        /// </summary>
        internal static string Error_External_Method {
            get {
                return ResourceManager.GetString("Error_External_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot execute open file instruction if a file is already open.
        /// </summary>
        internal static string Error_File_Already_Open {
            get {
                return ResourceManager.GetString("Error_File_Already_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot execute close file instruction if a file is not open.
        /// </summary>
        internal static string Error_File_Close_None_Open {
            get {
                return ResourceManager.GetString("Error_File_Close_None_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot perform file operations if no file is open. Run OFL (0xE0) first.
        /// </summary>
        internal static string Error_File_No_Open {
            get {
                return ResourceManager.GetString("Error_File_No_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot execute file read instruction. The end of the file has already been reached..
        /// </summary>
        internal static string Error_File_Read_End_Reached {
            get {
                return ResourceManager.GetString("Error_File_Read_End_Reached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot execute file read instruction if a file is not open.
        /// </summary>
        internal static string Error_File_Read_No_Open {
            get {
                return ResourceManager.GetString("Error_File_Read_No_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot execute open external function instruction if a function is already loaded.
        /// </summary>
        internal static string Error_Function_Already_Open {
            get {
                return ResourceManager.GetString("Error_Function_Already_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified external function is invalid or does not exist in the loaded external assembly.
        /// </summary>
        internal static string Error_Function_Invalid {
            get {
                return ResourceManager.GetString("Error_Function_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot execute instruction if an external function is not loaded.
        /// </summary>
        internal static string Error_Function_Not_Open {
            get {
                return ResourceManager.GetString("Error_Function_Not_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred trying to load the external function.
        /// </summary>
        internal static string Error_Function_Unknown {
            get {
                return ResourceManager.GetString("Error_Function_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given memory address does not correspond to the start of an allocated memory block..
        /// </summary>
        internal static string Error_Invalid_Memory_Block {
            get {
                return ResourceManager.GetString("Error_Invalid_Memory_Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory allocation failed. There may not be enough free contiguous memory remaining..
        /// </summary>
        internal static string Error_Memory_Allocation {
            get {
                return ResourceManager.GetString("Error_Memory_Allocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A program has not been loaded in this processor..
        /// </summary>
        internal static string Error_No_Program {
            get {
                return ResourceManager.GetString("Error_No_Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised extension set.
        /// </summary>
        internal static string Error_Opcode_Extension_Set {
            get {
                return ResourceManager.GetString("Error_Opcode_Extension_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised high opcode for the memory allocation extension set.
        /// </summary>
        internal static string Error_Opcode_High_Allocation {
            get {
                return ResourceManager.GetString("Error_Opcode_High_Allocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised high opcode for the base instruction set.
        /// </summary>
        internal static string Error_Opcode_High_Base {
            get {
                return ResourceManager.GetString("Error_Opcode_High_Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised high opcode for the extended base set.
        /// </summary>
        internal static string Error_Opcode_High_Extended {
            get {
                return ResourceManager.GetString("Error_Opcode_High_Extended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised high opcode for the external assembly extension set.
        /// </summary>
        internal static string Error_Opcode_High_External {
            get {
                return ResourceManager.GetString("Error_Opcode_High_External", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised high opcode for the file system extension set.
        /// </summary>
        internal static string Error_Opcode_High_FileSystem {
            get {
                return ResourceManager.GetString("Error_Opcode_High_FileSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised high opcode for the floating point extension set.
        /// </summary>
        internal static string Error_Opcode_High_FloatingPoint {
            get {
                return ResourceManager.GetString("Error_Opcode_High_FloatingPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised high opcode for the signed extension set.
        /// </summary>
        internal static string Error_Opcode_High_Signed {
            get {
                return ResourceManager.GetString("Error_Opcode_High_Signed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised high opcode for the terminal extension set.
        /// </summary>
        internal static string Error_Opcode_High_Terminal {
            get {
                return ResourceManager.GetString("Error_Opcode_High_Terminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised memory allocation extension set allocation low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_Allocation_Allocation {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_Allocation_Allocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised memory allocation extension set free low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_Allocation_Free {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_Allocation_Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised memory allocation extension set re-allocation low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_Allocation_Reallocation {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_Allocation_Reallocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised base instruction set addition low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_Base_Addition {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_Base_Addition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised base instruction set bitwise low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_Base_Bitwise {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_Base_Bitwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised base instruction set comparison low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_Base_Comparison {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_Base_Comparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised base instruction set console write low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_Base_ConsoleWrite {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_Base_ConsoleWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised base instruction set control low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_Base_Control {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_Base_Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised base instruction set division low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_Base_Division {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_Base_Division", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised base instruction set file operation low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_Base_FileOperation {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_Base_FileOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised base instruction set file write low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_Base_FileWrite {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_Base_FileWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised base instruction set large move low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_Base_LargeMove {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_Base_LargeMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised base instruction set multiplication low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_Base_Multiplication {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_Base_Multiplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised base instruction set reading low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_Base_Reading {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_Base_Reading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised base instruction set shifting low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_Base_Shifting {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_Base_Shifting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised base instruction set small move low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_Base_SmallMove {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_Base_SmallMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised base instruction set stack low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_Base_Stack {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_Base_Stack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised base instruction set subroutine low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_Base_Subroutine {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_Base_Subroutine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised base instruction set subtraction low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_Base_Subtraction {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_Base_Subtraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised extended base set byte swap low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_Extended_ByteSwap {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_Extended_ByteSwap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised extended base set halt low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_Extended_Halt {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_Extended_Halt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised extended base set processor query low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_Extended_InfoQuery {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_Extended_InfoQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised external assembly extension set calling low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_External_Call {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_External_Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised external assembly extension set closing low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_External_Close {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_External_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised external assembly extension set existence low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_External_Existence {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_External_Existence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised external assembly extension set loading low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_External_Load {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_External_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised file system extension set directory listing low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_FileSystem_BeginListing {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_FileSystem_BeginListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised file system extension set create directory low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_FileSystem_CreateDir {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_FileSystem_CreateDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised file system extension set delete directory low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_FileSystem_DeleteDir {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_FileSystem_DeleteDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised file system extension set directory existence low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_FileSystem_DirectoryExists {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_FileSystem_DirectoryExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised file system extension set listing get low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_FileSystem_ListingGet {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_FileSystem_ListingGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised file system extension set copy/move low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_FileSystem_Move {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_FileSystem_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised file system extension set file time get low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_FileSystem_TimeGet {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_FileSystem_TimeGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised file system extension set file time set low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_FileSystem_TimeSet {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_FileSystem_TimeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised file system extension set working directory low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_FileSystem_WorkingDir {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_FileSystem_WorkingDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised floating point extension set addition low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_FloatingPoint_Addition {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_FloatingPoint_Addition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised floating point extension set comparison low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_FloatingPoint_Comparison {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_FloatingPoint_Comparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised floating point extension set console write low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_FloatingPoint_ConsoleWrite {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_FloatingPoint_ConsoleWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised floating point extension set division low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_FloatingPoint_Division {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_FloatingPoint_Division", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised floating point extension set exponentiation low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_FloatingPoint_Exponentiation {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_FloatingPoint_Exponentiation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised floating point extension set file write low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_FloatingPoint_FileWrite {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_FloatingPoint_FileWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised floating point extension set float to int low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_FloatingPoint_FloatToInt {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_FloatingPoint_FloatToInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised floating point extension set int to float low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_FloatingPoint_IntToFloat {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_FloatingPoint_IntToFloat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised floating point extension set logarithm low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_FloatingPoint_Logarithm {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_FloatingPoint_Logarithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised floating point extension set multiplication low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_FloatingPoint_Multiplication {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_FloatingPoint_Multiplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised floating point extension set negate low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_FloatingPoint_Negate {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_FloatingPoint_Negate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised floating point extension set size conversion low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_FloatingPoint_SizeConversion {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_FloatingPoint_SizeConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised floating point extension set subtraction low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_FloatingPoint_Subtraction {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_FloatingPoint_Subtraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised floating point extension set trigonometry low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_FloatingPoint_Trigonometry {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_FloatingPoint_Trigonometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised signed extension set console write low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_Signed_ConsoleWrite {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_Signed_ConsoleWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised signed extension set division low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_Signed_Division {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_Signed_Division", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised signed extension set extend low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_Signed_Extend {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_Signed_Extend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised signed extension set file write low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_Signed_FileWrite {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_Signed_FileWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised signed extension set jump low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_Signed_Jump {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_Signed_Jump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised signed extension set large move low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_Signed_LargeMove {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_Signed_LargeMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised signed extension set negate low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_Signed_Negate {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_Signed_Negate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised signed extension set shifting low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_Signed_Shifting {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_Signed_Shifting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised signed extension set small move low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_Signed_SmallMove {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_Signed_SmallMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised terminal extension set beep low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_Terminal_Beep {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_Terminal_Beep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised terminal extension set clear low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_Terminal_Clear {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_Terminal_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised terminal extension set colour low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_Terminal_Colour {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_Terminal_Colour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised terminal extension set information getting low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_Terminal_GetPosition {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_Terminal_GetPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:X} is not a recognised terminal extension set position setting low opcode.
        /// </summary>
        internal static string Error_Opcode_Low_Terminal_SetPosition {
            get {
                return ResourceManager.GetString("Error_Opcode_Low_Terminal_SetPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program too large to fit in allocated memory. {0} bytes available, {1} given..
        /// </summary>
        internal static string Error_Program_Too_Large {
            get {
                return ResourceManager.GetString("Error_Program_Too_Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot write to read-only register {0}.
        /// </summary>
        internal static string Error_Read_Only_Register {
            get {
                return ResourceManager.GetString("Error_Read_Only_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stack has collided with already allocated memory.
        /// </summary>
        internal static string Error_Stack_Collide {
            get {
                return ResourceManager.GetString("Error_Stack_Collide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rso register is outside the range of available memory.
        /// </summary>
        internal static string Error_Stack_Out_Of_Range {
            get {
                return ResourceManager.GetString("Error_Stack_Out_Of_Range", resourceCulture);
            }
        }
    }
}
