# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  push:

jobs:
  build:

    strategy:
      matrix:
        build-os: [ubuntu-latest, windows-latest, macos-latest]
        runtime-target: [
          win-x64, win-x86, win-arm64,
          osx-x64, osx-arm64,
          linux-x64, linux-arm, linux-arm64
        ]

    runs-on: ${{ matrix.build-os }}

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Test Project
      run: dotnet test
    - name: Publish Project
      run: dotnet publish AssEmbly.csproj -p:PublishProfile="Properties/PublishProfiles/${{ matrix.runtime-target }}.pubxml" -p:TreatWarningsAsErrors=true -warnaserror
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: AssEmbly-${{ matrix.build-os }}-${{ matrix.runtime-target }}
        path: Publish/${{ matrix.runtime-target }}/AssEmbly.exe
        if-no-files-found: error
