# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Test .NET

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  push:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Test Project
        run: dotnet test -c Release

  build:
    strategy:
      matrix:
        runtime-target: [
          win-x64, win-x86, win-arm64,
          osx-x64, osx-arm64,
          linux-x64, linux-arm, linux-arm64
        ]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Publish Project
      run: dotnet publish AssEmbly.csproj -p:PublishProfile="Properties/PublishProfiles/${{ matrix.runtime-target }}.pubxml" -p:TreatWarningsAsErrors=true -warnaserror
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: AssEmbly-${{ matrix.runtime-target }}
        path: Publish/${{ matrix.runtime-target }}/
        if-no-files-found: error

  test-build-opts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install tqdm
        run: pip3 install tqdm
      - name: Test Build Option Combinations
        run: python3 Scripts/test_build_options.py
